#!/usr/bin/env bash
set -euo pipefail

# Expand environment variables in .env files for both VS Code and deployment scripts
# VS Code's envFile property and our launchers will both use the expanded .env files

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CONFIG_DIR="$ROOT_DIR/config"

expand_env_file() {
  local source_file="$1"
  local output_file="$2"
  
  # Read and expand the source file
  # We use a subshell to avoid polluting the current environment
  (
    set -a
    # shellcheck disable=SC1090
    source "$source_file"
    set +a
    
    # Write header
    echo "# Auto-generated expanded environment file" > "$output_file"
    echo "# Source: $source_file" >> "$output_file"
    echo "# Generated: $(date)" >> "$output_file"
    echo "# DO NOT EDIT - This file is automatically generated" >> "$output_file"
    echo "" >> "$output_file"
    
    # Export all variables with expanded values
    # Read the source file and expand each variable
    while IFS='=' read -r key value; do
      # Skip comments and empty lines
      [[ "$key" =~ ^#.*$ ]] && continue
      [[ -z "$key" ]] && continue
      
      # Expand the value using eval (safe since we control the input)
      expanded_value=$(eval echo "$value")
      echo "${key}=${expanded_value}" >> "$output_file"
    done < <(grep -v '^#' "$source_file" | grep -v '^$' || true)
  )
  
  echo "Expanded $source_file -> $output_file"
}

# If LUMOS_ENVIRONMENT is set, expand only that environment
if [ -n "${LUMOS_ENVIRONMENT:-}" ]; then
  ENV_FILE="$CONFIG_DIR/${LUMOS_ENVIRONMENT}.env"
  EXPANDED_FILE="$CONFIG_DIR/${LUMOS_ENVIRONMENT}.expanded.env"
  
  if [ ! -f "$ENV_FILE" ]; then
    echo "Error: Environment file not found: $ENV_FILE" >&2
    exit 1
  fi
  
  expand_env_file "$ENV_FILE" "$EXPANDED_FILE"
else
  # Expand all non-template environment files
  echo "Expanding all environment files in $CONFIG_DIR..."
  
  for env_file in "$CONFIG_DIR"/*.env; do
    if [ -f "$env_file" ]; then
      basename=$(basename "$env_file" .env)
      
      # Skip template and already-expanded files
      if [[ "$basename" == "template" || "$basename" == *.expanded ]]; then
        continue
      fi
      
      expanded_file="$CONFIG_DIR/${basename}.expanded.env"
      expand_env_file "$env_file" "$expanded_file"
    fi
  done
fi

echo "Environment file(s) expanded successfully"

