export enum OrderStatus {
  OPEN = 'OPEN',
  EXECUTED = 'EXECUTED',
  CANCELLED = 'CANCELLED',
  INDIVIDUAL_FILLS = 'INDIVIDUAL_FILLS',
  CANCEL_REQUESTED = 'CANCEL_REQUESTED',
  EXPIRED = 'EXPIRED',
  REJECTED = 'REJECTED'
}
